### ISSUE TITLE
access datasets through `fsspec` and `adlfs`

### ISSUE THREAD

**Issue by ngam** [microsoft/PlanetaryComputerDataCatalog#348]
Hi, thanks for providing these datasets. I would like to access the goes-cmi dataset through `fsspec` and `adlfs` (i.e. `pip install fsspec adlfs`), but I cannot seem to figure it out.

It seems the `account_name` associated with these datasets is `pcstacitems`? That doesn't seem to be documented. Anyway, I cannot get a straightforward anonymous access to any dataset. For example, this code

```python
import fsspec
fs = fsspec.filesystem("abfs", account_name="pcstacitems")
fs.ls("/")  # or fs.ls("abfs://items/" and so on
```

errors with

```
ErrorCode:NoAuthenticationInformation
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>NoAuthenticationInformation</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
```

Or sometimes with things like "not found". Is there an easy way to access these datasets through fsspec? I also tried initiating a SAS token, but to no avail. 

I also tried to figure out the details from this, but to no avail. https://planetarycomputer.microsoft.com/api/stac/v1/collections/goes-cmi/items/OR_ABI-L2-F-M6_G17_s20222200300319

For example, this also didn't work.

```python
import fsspec
fs = fsspec.filesystem("abfs", account_name="goeseuwest")
fs.ls("noaa-goes-cogs/goes-17")
```

It would be nice if these datasets could be provided more transparently. I understand the desire to make them easy to use via Jupyter notebooks (like the examples) but I found those to be extremely hard for proper application/deployment (beyond the simple examples). For comparison, the GOES datasets could be easily used on AWS and GCP without any issue:

```python
import fsspec
gcp = fsspec.filesystem("gs", token="anon", anon=True)
gcp.ls("gcp-public-data-goes-17/")  # prints ['gcp-public-data-goes-17/ABI-L1b-RadC'...
aws = fsspec.filesystem("s3", token="anon", anon=True)
aws.ls("noaa-goes17/")  # prints ['noaa-goes17/ABI-L1b-RadC', 'no...

```
Now trying:

```python
# now trying:
az = fsspec.filesystem("abfs", token="anon", anon=True)
```
results in this error:
```

ValueError: Must provide either a connection_string or account_name with credentials!!
```

Thank you!

**Comment by TomAugspurger** [comment]
>  I understand the desire to make them easy to use via Jupyter notebooks (like the examples) but I found those to be extremely hard for proper application/deployment (beyond the simple examples).

I'd be curious to hear more about what you found challenging about the workflow presented in the notebook, if you're able to share. We have users accessing the data via STAC in production / application environments too.

**Comment by TomAugspurger** [comment]
Thanks for the feedback!

> (especially in the containers/images repo).

I assume you're referring to https://github.com/microsoft/planetary-computer-containers/pull/38 and https://github.com/microsoft/planetary-computer-containers/pull/39. I am indeed happy to review those. You happened to submit those at a time when my attention was elsewhere. I don't get to spend as much time on maintaining the Hub as I'd like, since we have so many priorities. Though if you do reopen those I'll need a bit of time before I'm able to review them since I'm in the middle of preparing an AKS cluster migration for our Hub. I'd love to have an up-to-date tensorflow / jax image.

>> Did you see https://planetarycomputer.microsoft.com/dataset/goes-cmi#Example-Notebook?

> Yes, I have looked at this many times (see below for the fuller answer on what I find challenging and draining about the example workflows)

Yeah, sorry, I didn't see that you'd referenced that in your original post, which lead to my [followup post](https://github.com/microsoft/PlanetaryComputerDataCatalog/issues/348#issuecomment-1209470980). Apologies for missing that.

It sounds like our [Introduction to STAC](https://planetarycomputer.microsoft.com/docs/quickstarts/reading-stac/) could use improving / additional cross-linking. (In this case, we're implementing the STAC-API and will return any items intersecting with the user-providing `bbox`; I'll update the examples to make that clearer).

> Funnily enough, the plot presented in the notebook above uses the GOES x and y coordinates instead of whatever these bbox coordinates are (I know, they're lons and lats, but they're organized in a weird way).

Yes, that's a STAC detail that could be better explained: STAC items are GeoJSON features and so the `bbox` and `geometry` are always in WGS84 latitude / longitude. The assets themselves can be in whatever native projection they need (and the properties under the `proj` field capture this). I'll add that to the STAC introduction notebook. Thanks for pointing it out as a source of confusion.

> but a balance must be struck between ease for users who nothing and users who are comfortable with numpy arrays and so on.

Indeed, we do find STAC useful. But we are also happy that the raw assets are available directly from blob storage. If you're more comfortable with that workflow, and the STAC API isn't providing anything useful, then you're free to go straight to the assets in blob storage using `adlfs` / `azure.storage.blob` / REST APIs. Regardless of whether not you're going through STAC, you're still accessing the same raw ndarrays from Azure Blob Storage.

I'll update the introduction quickstarts to share a direct to blob storage example.

> Instead, what I ended up doing was basically download TBs of data locally and then rely on the using the file names and time variable provided by the netcdf4 variables/keys to assemble my data pipeline and it worked very nicely.

In general, we recommend against this type of workflow and recommend a pangeo-style workflow that [streams data directly into memory](https://medium.com/pangeo/intake-stac-nasa-4cd78d6246b7). That said, if you have the local storage and are bottlenecked by network bandwidth (which I guess can be common for deep learning workflows?), it might make sense to start your pipeline by downloading data locally. Fortunately, you have that option since you have direct access to the files in blob storage.

This does highlight one of the reasons we (as a data provider) like STAC so much. Since we're hosting many different datasets, STAC gives us a standardized way to express the metadata that you're extracting from the filenames. Other datasets use different naming conventions, so you'll need custom code to parse the paths of each dataset you're using. But if you're only using one or a few datasets, that's not a big deal.

> Now, I am trying to expand the project and I found using fsspec to be the most intuitive and easiest coupled with h5py, because I could easily transfer my code from one provider to another, including even "local":

Just a note, depending on the files you might see pretty poor performance when opening the metadata from NetCDF files from Blob Storage (https://matthewrocklin.com/blog/work/2018/02/06/hdf-in-the-cloud). But perhaps that's not an issue for your workflow. Either way, if you're reading all of the *data* from a NetCDF file anyway, it'll be faster to download it locally before opening it. You'll be accessing the same number of bytes, but doing it in fewer HTTP requests.

> I previously tried using the xarray package and I found it significantly slower than the plain netCDF4 locally, so I stopped using it even though xarray is way more convenient to use... Am I missing/messing something here?

It's a bit hard to say, but if you're accessing the NetCDF files from Blob Storage then my previous note about HDF in the cloud might be the culprit. xarray tends to do a bit more work, and might load a bit more metadata than `h5py.File` / however netCDF4 opens a file. https://docs.xarray.dev/en/stable/generated/xarray.open_dataset.html documents a few keywords that should get xarray pretty close to the underlying engine though: `decode_cf`, `decode_times`, `use_cftime`, etc.

> You mention COGs and I believe I read that they can be really efficient and nice to use: Could you please provide me with a reference so that I can try to use them to see if they can fit nicely in my workflow?

https://planetarycomputer.microsoft.com/dataset/goes-cmi#Example-Notebook and https://github.com/microsoft/PlanetaryComputerExamples/blob/main/tutorials/hurricane-florence-animation.ipynb, which use STAC, hopefully gives a decent overview.

Unfortunately, I ran into https://github.com/opendatacube/odc-stac/issues/85, so I'm still debugging that. I'll get back to you on a more complete (possible) workflow. That said, if you have something that works using Blob Storage directly, then by all means use that!

One question about this:

> sampled 4x daily (00, 06, 12, 18 hrs) as many as available per hour (maybe 10) for at least an entire year (so at least, (4)(10)(365)

Which GOES image types are you interested in? There was a comment about "CONUS". And do you want a single ndarray with assets from both GOES-16 and 17, or would those be in two separate ndarrays?

It looks like there are 6 CONUS assets per hour:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/1312546/183757810-35b5b75b-57d5-4b63-9dab-2da20c45df04.png">

---

Thanks again for the critical feedback, I really do appreciate it. And let me know if I missed anything. I'm going through all of our notebooks following some changes in https://github.com/stac-utils/pystac-client, so I'll include some of your suggestions here:

1. Show examples using fsspec / adlfs directly
2. Cover some of the STAC API fundamentals like `limit`, coordinate systems, `query`, intersections, etc.

**Comment by TomAugspurger** [comment]
Thanks. I’ve been out sick the past couple days but I’ll take a look when I’m back.
